// Image optimization pipeline.
//
// For every JPEG in /img this generates:
//   1. A set of downscaled width variants (for responsive <img srcset>), so the
//      browser downloads only as many pixels as the layout needs — including the
//      extra pixels Retina/HiDPI displays ask for via devicePixelRatio.
//   2. A tiny inline base64 LQIP (Low-Quality Image Placeholder) that paints
//      instantly while the real image streams in / lazy-loads.
//
// Variants are written to /public/responsive (served verbatim by Vite under the
// configured base path). A manifest is written to src/data/images.js.
//
// Regenerate after adding/replacing images:  npm run images
//
// Uses macOS `sips` so there are no extra npm dependencies.

import { execFileSync } from 'node:child_process'
import {
  readdirSync, readFileSync, writeFileSync, mkdtempSync, rmSync, mkdirSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const IMG_DIR = join(ROOT, 'img')
const OUT_DIR = join(ROOT, 'public', 'responsive')
const OUT_REL = 'responsive' // path under the served base, e.g. /poi/responsive/...
const MANIFEST = join(ROOT, 'src', 'data', 'images.js')

const TARGET_WIDTHS = [360, 540, 720, 900, 1080] // candidate widths, capped at source
const JPEG_QUALITY = 72
const PLACEHOLDER_EDGE = 24
const PLACEHOLDER_QUALITY = 40

function dims(file) {
  const out = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', file]).toString()
  const w = Number(out.match(/pixelWidth:\s*(\d+)/)[1])
  const h = Number(out.match(/pixelHeight:\s*(\d+)/)[1])
  return { w, h }
}

mkdirSync(OUT_DIR, { recursive: true })
const tmp = mkdtempSync(join(tmpdir(), 'imgopt-'))

try {
  const files = readdirSync(IMG_DIR).filter((f) => /\.jpe?g$/i.test(f)).sort()
  const manifest = {}

  for (const file of files) {
    const src = join(IMG_DIR, file)
    const { w: srcW, h: srcH } = dims(src)
    const stem = basename(file).replace(/\.jpe?g$/i, '')

    // Widths to actually produce: never upscale past the source.
    let widths = TARGET_WIDTHS.filter((w) => w <= srcW)
    if (widths.length === 0) widths = [srcW]

    const variants = widths.map((w) => {
      const outName = `${stem}-${w}.jpg`
      execFileSync('sips', [
        '--resampleWidth', String(w),
        '-s', 'format', 'jpeg',
        '-s', 'formatOptions', String(JPEG_QUALITY),
        src, '--out', join(OUT_DIR, outName),
      ], { stdio: 'ignore' })
      return { w, src: `${OUT_REL}/${outName}` }
    })

    // Tiny inline placeholder.
    const phOut = join(tmp, `${stem}-ph.jpg`)
    execFileSync('sips', [
      '-Z', String(PLACEHOLDER_EDGE),
      '-s', 'format', 'jpeg',
      '-s', 'formatOptions', String(PLACEHOLDER_QUALITY),
      src, '--out', phOut,
    ], { stdio: 'ignore' })
    const placeholder = `data:image/jpeg;base64,${readFileSync(phOut).toString('base64')}`

    manifest[file] = { width: srcW, height: srcH, variants, placeholder }
  }

  const body =
    '// AUTO-GENERATED by scripts/gen-images.mjs — do not edit by hand.\n' +
    '// Run `npm run images` to regenerate after adding/replacing images in /img.\n\n' +
    'const images = ' + JSON.stringify(manifest, null, 2) + '\n\n' +
    '// Resolve a responsive <img> prop bundle for an image (keyed by its /img\n' +
    '// filename, e.g. "about001.jpg"). srcSet lets the browser pick the right\n' +
    '// resolution for the viewport AND the display density (Retina). The chosen\n' +
    '// `sizes` string tells it how wide the image renders at each breakpoint.\n' +
    'export function imgProps(file) {\n' +
    '  const base = import.meta.env.BASE_URL\n' +
    '  const entry = images[file]\n' +
    '  if (!entry) throw new Error(`No optimized image for "${file}" — run npm run images`)\n' +
    '  const srcSet = entry.variants.map((v) => `${base}${v.src} ${v.w}w`).join(", ")\n' +
    '  const largest = entry.variants[entry.variants.length - 1]\n' +
    '  return {\n' +
    '    src: `${base}${largest.src}`,\n' +
    '    srcSet,\n' +
    '    width: entry.width,\n' +
    '    height: entry.height,\n' +
    '    placeholder: entry.placeholder,\n' +
    '  }\n' +
    '}\n\n' +
    'export default images\n'

  writeFileSync(MANIFEST, body)

  const totalVariants = Object.values(manifest).reduce((n, e) => n + e.variants.length, 0)
  console.log(`Generated ${totalVariants} variants for ${files.length} images → public/${OUT_REL}/`)
  console.log(`Wrote manifest → src/data/images.js`)
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
